<?php

/**
 * Implementation of hook_autoload_info().
 */
function update_feed_api_autoload_info() {
  $path = drupal_get_path('module','update_feed_api').'/includes/';
  return array(
    'FeedEntryContainer' => array(
      'file' => 'feedentrycontainer.class.inc',
      'file path' => $path,
    ),
    'Project' => array(
      'file' => 'project.class.inc',
      'file path' => $path,
    ),
    'Release' => array(
      'file' => 'release.class.inc',
      'file path' => $path,
    ),
    'Project_factory' => array(
      'file' => 'factories.class.inc',
      'file path' => $path,
    ),
  );
}

function update_feed_api_menu() {
  return array(
    'update_feed_api_test' => array(
       'page callback' => '_update_feed_api_test',
       'access callback' => TRUE
    ),
  );
}

function _update_feed_api_test() {
  $server_key = 'testserver';
  $info = array(
    'title' => 'Signup',
    'short_name' => 'signup',
    'api_version' => '6.x',
    'recommended_major' => '1',
    'supported_majors' => '1',
    'default_major' => '1',
    'project_status' => 'published',
    'link' => 'http://drupal.org/project/signup',
  );
  $terms = array(
    'Projects' => 'module'
  );
  /*$project = new Project($info, $terms, $server_key);
  $project->save();*/
  
  $project = Project_factory::load_project('testserver','signup');
  $project->set_info('api_version', '7.x');
  $project->save();
  return '';
}