<?php

require_once 'update_feed_cck.field.inc';
require_once 'update_feed_cck.widget.inc';

function update_feed_cck_menu() {
  $items = array();
  $items['update_feed_cck/autocomplete'] = array(
    'title' => 'Update feed cck autocompletition',
		'page callback' => '_update_feed_cck_autocomplete',
    'access arguments' => array('update feed cck autocompletition'), 
    'type' => MENU_CALLBACK
  );
  return $items;
}

function update_feed_cck_perm() {
  return array('update feed cck autocompletition');
}

function _update_feed_cck_autocomplete($field_name, $string = '') {
  $fields = content_fields();
  $field = $fields[$field_name];
  $match = isset($field['widget']['autocomplete_match']) ? $field['widget']['autocomplete_match'] : 'contains';
  $matches = array();

  $references = _nodereference_potential_references($field, $string, $match, array(), 10);
  foreach ($references as $id => $row) {
    // Add a class wrapper for a few required CSS overrides.
    $matches[$row['title'] ." [nid:$id]"] = '<div class="reference-autocomplete">'. $row['rendered'] . '</div>';
  }
  drupal_json($matches);
}
}
  
/**
 * Implementation of hook_field_info().
 */
function update_feed_cck_field_info() {
  return array(
    'update_feed_cck' => array(
      'label' => t('Update feed'), 
      'description' => t('A field for a module fetched by the update_feed_api'),
    ),
  );
}

/**
 * Implementation of hook_widget_info().
 */
function update_feed_cck_widget_info() {
  return array(
    'update_feed_cck_widget' => array(
      'field types' => array('update_feed_cck'),
      'label' => t('Update feed select dialog'),
      'multiple values' => CONTENT_HANDLE_CORE,
      'callbacks' => array(
          'default value' => CONTENT_CALLBACK_DEFAULT,
      ),
    ),
  );
}

/**
 * Implementation of CCK's hook_field().
 */
function update_feed_cck_field($op, $node, $field, &$items, $teaser, $page) {
  module_load_include('inc', 'update_feed_cck', 'update_feed_cck.field');
  $op = str_replace(' ', '_', $op);
  // add filefield specific handlers...
  $function = 'update_feed_cck_field_'. $op;
  if (function_exists($function)) {
    return $function($node, $field, $items, $teaser, $page);
  }
}

/**
 *  Thats our own FAPI element for our CCK widget
 */

function update_feed_cck_theme() {
  return array(
    'update_feed_module' => array (
        'arguments' => array('element' => NULL),
    ),
  );
}

function update_feed_cck_elements() {
  return array(
  'update_feed_module' => array(
    '#input' => TRUE,
    '#delta' => 0,
    '#process' => array('update_feed_cck_update_feed_module_process'),
    '#autocomplete_path' => FALSE,
    ),
  );
}


function theme_update_feed_module($element) {
  return theme('form_element', $element, $element['#children']);
}
